package com.justinligny.cqrs.entities;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.sql.Timestamp;

/**
 *  <h1>DbEntity Class</h1> <br>
 *
 *  <p>The {@code DbEntity} class serves as a base entity class for all entities in
 *  the application that need to be persisted in the database. It provides common
 *  fields such as an auto-generated {@code id}, as well as timestamps for tracking
 *  the creation and last update times of the entity.</p> <br>
 *
 *  <p>This class is annotated with {@code @MappedSuperclass}, which means it is
 *  not directly persisted as an entity but provides the mapping for its
 *  subclasses.</p> <br>
 *
 *  <p>The {@code id} field is automatically generated using the
 *  {@code GenerationType.IDENTITY} strategy, which means the value will be assigned
 *  by the database upon insertion.</p> <br>
 *
 *  <p>The {@code updatedAt} field is automatically updated with the current
 *  timestamp whenever the entity is updated, thanks to the {@code @UpdateTimestamp}
 *  annotation.</p> <br>
 *
 *  <p>The {@code createdAt} field is automatically set to the current timestamp
 *  when the entity is first created, thanks to the {@code @CreationTimestamp}
 *  annotation.</p> <br>
 *
 *  <p>Subclasses of {@code DbEntity} will inherit these common properties and can
 *  be used in JPA repositories for CRUD operations.</p> <br>
 *
 *  @author Justin Ligny
 *  @since 1.0.1
 */
@MappedSuperclass
@Data
public abstract class DbEntity {

    /**
     * The unique identifier for the entity.
     * This field is automatically generated by the database.
     *
     * @since 1.0.1
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    /**
     * The timestamp of the last update made to the entity.
     * This field is automatically updated when the entity is modified.
     *
     * @since 1.0.1
     */
    @UpdateTimestamp
    protected Timestamp updatedAt;

    /**
     * The timestamp of when the entity was created.
     * This field is automatically set when the entity is first persisted.
     *
     * @since 1.0.1
     */
    @CreationTimestamp
    protected Timestamp createdAt;
}
